#!/usr/bin/env php
<?php
/**
 * Pano console bootstrap file.
 *
 */

defined('PANO_ROOT') or define('PANO_ROOT', __DIR__);
defined('PANO_APP_ROOT') or define('PANO_APP_ROOT', PANO_ROOT . '/pano/');

require PANO_APP_ROOT . 'console/pano-cli';